# AICP Intership Task Week 1


### Import Libraries

In [2]:
import numpy as np

## Question no 1
Write a Numpy program to create an array of all even integers from 30 to 70
### Answer

In [34]:
arr = np.arange(30, 70, 2)

print('Array of all even numbers from 30 to 70:',arr)

Array of all even numbers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


## Question No 2
Write a numpy program to generate an array of 15 random numbers from a standard normal distribution
### Answer

In [41]:
arr1 = np.random.randint(30, size=15)

print('Array of 15 ramdom numbers',arr1)

Array of 15 ramdom numbers [26 17  0 16 14 20 12 26 27  3 15 25 14 28 25]


## Question No 3
How to compute the cross-product of two matrices in Numpy?
### Answer

In [31]:
matrix1 = np.array([[10, 12, 11], [4, 9, 6], [9, 8, 5]])
matrix2 = np.array([[4, 10, 17], [6,8, 4], [7, 12, 10]])


cross_product = np.cross(matrix1, matrix2)

print('Cross product of matrix1 and matrix2 is:\n',cross_product)

Cross product of matrix1 and matrix2 is:
 [[  94 -126   52]
 [ -12   20  -22]
 [  20  -55   52]]


## Question No 4 
How to compute the determinant of an array using Numpy?
### Answer

In [42]:
arr2 = np.array([[3, 2], [1, 4]])

det = np.linalg.det(arr2)

print('Determinant of the array is:',det)

Determinant of the array is: 10.000000000000002


# Question No 5
How to create a 3x3x3 array with the random values using Numpy?
### Answer

In [43]:
array3 = np.random.randint(1,50,size=(3, 3, 3))

print(array3)

[[[48 10 25]
  [10 43 22]
  [44 16 46]]

 [[12 14 26]
  [16 35 22]
  [ 7  7 30]]

 [[19 27 31]
  [33 14 22]
  [40 34 20]]]


## Question No 6
How to create a 5x5 array with ramdom values and find the minimum and maximum values using Numpy?
### Answer

In [50]:
arr4 = np.random.randint(1,50,size=(5, 5))

print("Array:\n",arr4)

min_value = np.min(arr4)
max_value = np.max(arr4)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Array:
 [[44 41 43 20  8]
 [13  8  3 39 22]
 [42 23 39  8 47]
 [ 1 11  6 49 31]
 [38 15 17 34  9]]
Minimum value: 1
Maximum value: 49


## Question No 7
How to compute the mean, standard deviation, and variance of a given array along the second axis in Numpy?
### Answer

In [52]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])

mean = np.mean(arr5, axis=1)

std_dev = np.std(arr5, axis=1)

variance = np.var(arr5, axis=1)

print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_dev)
print("Variance along the second axis:", variance)

Mean along the second axis: [2. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
